ALTER SESSION SET NLS_DATE_FORMAT = "DD/MM/YYYY";
-----------
INSERT INTO Oceny VALUES (1, 1, 'niedostateczna');
INSERT INTO Oceny VALUES (2, 1.75, 'dopuszczjaca minus');
INSERT INTO Oceny VALUES (3, 2, 'dopuszczjaca');
INSERT INTO Oceny VALUES (4, 2.5, 'dopuszczjaca plus');
INSERT INTO Oceny VALUES (5, 2.75, 'dostateczna minus');
INSERT INTO Oceny VALUES (6, 3, 'dostateczna');
INSERT INTO Oceny VALUES (7, 3.5, 'dostateczna plus');
INSERT INTO Oceny VALUES (8, 3.75, 'dobra minus');
INSERT INTO Oceny VALUES (9, 4, 'dobra');
INSERT INTO Oceny VALUES (10, 4.5, 'dobra plus');
INSERT INTO Oceny VALUES (11, 4.75, 'bardzo dobra minus');
INSERT INTO Oceny VALUES (12, 5, 'bardzo dobra');
INSERT INTO Oceny VALUES (13, 5.5, 'bardzo dobra plus');
INSERT INTO Oceny VALUES (14, 5.75, 'celujaca minus');
INSERT INTO Oceny VALUES (15, 6, 'celujaca');
-----------
INSERT INTO Nauczyciele VALUES (1, 'Marian', 'Ruwacki', '25/01/1987');
INSERT INTO Nauczyciele VALUES (2, 'Bartlomiej', 'Ruwecki', '10/03/1970');
INSERT INTO Nauczyciele VALUES (3, 'Jakub', 'Towecki', '20/01/1980');
INSERT INTO Nauczyciele VALUES (4, 'Piotr', 'Rowecki', '15/07/1988');
INSERT INTO Nauczyciele VALUES (5, 'Jakub', 'Gowacki', '27/01/1991');
INSERT INTO Nauczyciele VALUES (6, 'Marcin', 'Rowicki', '11/01/1989');
INSERT INTO Nauczyciele VALUES (7, 'Hubert', 'Gowecki', '26/07/1997');
INSERT INTO Nauczyciele VALUES (8, 'Jakub', 'Biwicki', '23/04/1978');
INSERT INTO Nauczyciele VALUES (9, 'Bartlomiej', 'Drzewacki', '19/02/1994');
INSERT INTO Nauczyciele VALUES (10, 'Bartlomiej', 'Mowecki', '12/07/1986');
INSERT INTO Nauczyciele VALUES (11, 'Marcin', 'Rowacki', '16/04/1978');
INSERT INTO Nauczyciele VALUES (12, 'Jakub', 'Ruwacki', '17/08/1988');
INSERT INTO Nauczyciele VALUES (13, 'Tomasz', 'Muwicki', '22/05/1978');
INSERT INTO Nauczyciele VALUES (14, 'Bartosz', 'Odrzewicki', '18/06/1992');
INSERT INTO Nauczyciele VALUES (15, 'Tomasz', 'Odrzewacki', '17/04/1999');
INSERT INTO Nauczyciele VALUES (16, 'Bartosz', 'Mowecki', '10/05/2003');
INSERT INTO Nauczyciele VALUES (17, 'Piotr', 'Ruwacki', '22/01/1993');
INSERT INTO Nauczyciele VALUES (18, 'Bartosz', 'Kowicki', '16/08/1983');
INSERT INTO Nauczyciele VALUES (19, 'Piotr', 'Drzewacki', '20/03/1979');
INSERT INTO Nauczyciele VALUES (20, 'Marcin', 'Muwacki', '16/07/2004');
INSERT INTO Nauczyciele VALUES (21, 'Hubert', 'Krzewecki', '23/02/1988');
INSERT INTO Nauczyciele VALUES (22, 'Jakub', 'Przewecki', '27/03/1984');
INSERT INTO Nauczyciele VALUES (23, 'Tomasz', 'Drzewecki', '23/08/1982');
INSERT INTO Nauczyciele VALUES (24, 'Hubert', 'Odrzewacki', '12/01/2001');
-----------
INSERT INTO Przedmioty VALUES (1, 'matematyka');
INSERT INTO Przedmioty VALUES (2, 'jezyk polski');
INSERT INTO Przedmioty VALUES (3, 'jezyk angielski');
INSERT INTO Przedmioty VALUES (4, 'biologia');
INSERT INTO Przedmioty VALUES (5, 'chemia');
INSERT INTO Przedmioty VALUES (6, 'historia');
-----------
INSERT INTO Klasy VALUES (1, 1, 'A', 5);
INSERT INTO Klasy VALUES (2, 1, 'B', 6);
INSERT INTO Klasy VALUES (3, 1, 'C', 7);
INSERT INTO Klasy VALUES (4, 1, 'D', 8);
INSERT INTO Klasy VALUES (5, 2, 'A', 9);
INSERT INTO Klasy VALUES (6, 2, 'B', 10);
INSERT INTO Klasy VALUES (7, 2, 'C', 11);
INSERT INTO Klasy VALUES (8, 2, 'D', 12);
INSERT INTO Klasy VALUES (9, 3, 'A', 13);
INSERT INTO Klasy VALUES (10, 3, 'B', 14);
INSERT INTO Klasy VALUES (11, 3, 'C', 15);
INSERT INTO Klasy VALUES (12, 3, 'D', 16);
-----------
INSERT INTO Uczniowie VALUES (1, 'Marian', 'Rowicki', 1);
INSERT INTO Uczniowie VALUES (2, 'Bartlomiej', 'Mowacki', 1);
INSERT INTO Uczniowie VALUES (3, 'Jakub', 'Ruwecki', 1);
INSERT INTO Uczniowie VALUES (4, 'Jakub', 'Biwacki', 1);
INSERT INTO Uczniowie VALUES (5, 'Hubert', 'Drzewacki', 1);
INSERT INTO Uczniowie VALUES (6, 'Wojciech', 'Gowicki', 1);
INSERT INTO Uczniowie VALUES (7, 'Bartosz', 'Gowicki', 1);
INSERT INTO Uczniowie VALUES (8, 'Jakub', 'Ruwecki', 1);
INSERT INTO Uczniowie VALUES (9, 'Jakub', 'Biwacki', 1);
INSERT INTO Uczniowie VALUES (10, 'Hubert', 'Drzewacki', 1);
INSERT INTO Uczniowie VALUES (11, 'Wojciech', 'Gowicki', 1);
INSERT INTO Uczniowie VALUES (12, 'Bartosz', 'Gowicki', 1);
INSERT INTO Uczniowie VALUES (13, 'Jakub', 'Ruwecki', 1);
INSERT INTO Uczniowie VALUES (14, 'Jakub', 'Biwacki', 1);
INSERT INTO Uczniowie VALUES (15, 'Hubert', 'Drzewacki', 1);
INSERT INTO Uczniowie VALUES (16, 'Wojciech', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (17, 'Bartosz', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (18, 'Jakub', 'Ruwecki', 2);
INSERT INTO Uczniowie VALUES (19, 'Jakub', 'Biwacki', 2);
INSERT INTO Uczniowie VALUES (20, 'Hubert', 'Drzewacki', 2);
INSERT INTO Uczniowie VALUES (21, 'Wojciech', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (22, 'Bartosz', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (23, 'Jakub', 'Ruwecki', 2);
INSERT INTO Uczniowie VALUES (24, 'Jakub', 'Biwacki', 2);
INSERT INTO Uczniowie VALUES (25, 'Hubert', 'Drzewacki', 2);
INSERT INTO Uczniowie VALUES (26, 'Wojciech', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (27, 'Bartosz', 'Gowicki', 2);
INSERT INTO Uczniowie VALUES (28, 'Jakub', 'Ruwecki', 2);
INSERT INTO Uczniowie VALUES (29, 'Jakub', 'Biwacki', 2);
INSERT INTO Uczniowie VALUES (30, 'Hubert', 'Drzewacki', 2);
INSERT INTO Uczniowie VALUES (31, 'Wojciech', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (32, 'Bartosz', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (33, 'Jakub', 'Ruwecki', 3);
INSERT INTO Uczniowie VALUES (34, 'Jakub', 'Biwacki', 3);
INSERT INTO Uczniowie VALUES (35, 'Hubert', 'Drzewacki', 3);
INSERT INTO Uczniowie VALUES (36, 'Wojciech', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (37, 'Bartosz', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (38, 'Jakub', 'Ruwecki', 3);
INSERT INTO Uczniowie VALUES (39, 'Jakub', 'Biwacki', 3);
INSERT INTO Uczniowie VALUES (40, 'Hubert', 'Drzewacki', 3);
INSERT INTO Uczniowie VALUES (41, 'Wojciech', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (42, 'Bartosz', 'Gowicki', 3);
INSERT INTO Uczniowie VALUES (43, 'Jakub', 'Ruwecki', 3);
INSERT INTO Uczniowie VALUES (44, 'Jakub', 'Biwacki', 3);
INSERT INTO Uczniowie VALUES (45, 'Hubert', 'Drzewacki', 3);
INSERT INTO Uczniowie VALUES (46, 'Wojciech', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (47, 'Bartosz', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (48, 'Jakub', 'Ruwecki', 4);
INSERT INTO Uczniowie VALUES (49, 'Jakub', 'Biwacki', 4);
INSERT INTO Uczniowie VALUES (50, 'Hubert', 'Drzewacki', 4);
INSERT INTO Uczniowie VALUES (51, 'Wojciech', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (52, 'Bartosz', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (53, 'Jakub', 'Ruwecki', 4);
INSERT INTO Uczniowie VALUES (54, 'Jakub', 'Biwacki', 4);
INSERT INTO Uczniowie VALUES (55, 'Hubert', 'Drzewacki', 4);
INSERT INTO Uczniowie VALUES (56, 'Wojciech', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (57, 'Bartosz', 'Gowicki', 4);
INSERT INTO Uczniowie VALUES (58, 'Jakub', 'Ruwecki', 4);
INSERT INTO Uczniowie VALUES (59, 'Jakub', 'Biwacki', 4);
INSERT INTO Uczniowie VALUES (60, 'Hubert', 'Drzewacki', 4);
INSERT INTO Uczniowie VALUES (61, 'Wojciech', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (62, 'Bartosz', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (63, 'Jakub', 'Ruwecki', 5);
INSERT INTO Uczniowie VALUES (64, 'Jakub', 'Biwacki', 5);
INSERT INTO Uczniowie VALUES (65, 'Hubert', 'Drzewacki', 5);
INSERT INTO Uczniowie VALUES (66, 'Wojciech', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (67, 'Bartosz', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (68, 'Jakub', 'Ruwecki', 5);
INSERT INTO Uczniowie VALUES (69, 'Jakub', 'Biwacki', 5);
INSERT INTO Uczniowie VALUES (70, 'Hubert', 'Drzewacki', 5);
INSERT INTO Uczniowie VALUES (71, 'Wojciech', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (72, 'Bartosz', 'Gowicki', 5);
INSERT INTO Uczniowie VALUES (73, 'Jakub', 'Ruwecki', 5);
INSERT INTO Uczniowie VALUES (74, 'Jakub', 'Biwacki', 5);
INSERT INTO Uczniowie VALUES (75, 'Hubert', 'Drzewacki', 5);
INSERT INTO Uczniowie VALUES (76, 'Wojciech', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (77, 'Bartosz', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (78, 'Jakub', 'Ruwecki', 6);
INSERT INTO Uczniowie VALUES (79, 'Jakub', 'Biwacki', 6);
INSERT INTO Uczniowie VALUES (80, 'Hubert', 'Drzewacki', 6);
INSERT INTO Uczniowie VALUES (81, 'Wojciech', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (82, 'Bartosz', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (83, 'Jakub', 'Ruwecki', 6);
INSERT INTO Uczniowie VALUES (84, 'Jakub', 'Biwacki', 6);
INSERT INTO Uczniowie VALUES (85, 'Hubert', 'Drzewacki', 6);
INSERT INTO Uczniowie VALUES (86, 'Wojciech', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (87, 'Bartosz', 'Gowicki', 6);
INSERT INTO Uczniowie VALUES (88, 'Jakub', 'Ruwecki', 6);
INSERT INTO Uczniowie VALUES (89, 'Jakub', 'Biwacki', 6);
INSERT INTO Uczniowie VALUES (90, 'Hubert', 'Drzewacki', 6);
INSERT INTO Uczniowie VALUES (91, 'Wojciech', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (92, 'Bartosz', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (93, 'Jakub', 'Ruwecki', 7);
INSERT INTO Uczniowie VALUES (94, 'Jakub', 'Biwacki', 7);
INSERT INTO Uczniowie VALUES (95, 'Hubert', 'Drzewacki', 7);
INSERT INTO Uczniowie VALUES (96, 'Wojciech', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (97, 'Bartosz', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (98, 'Jakub', 'Ruwecki', 7);
INSERT INTO Uczniowie VALUES (99, 'Jakub', 'Biwacki', 7);
INSERT INTO Uczniowie VALUES (100, 'Hubert', 'Drzewacki', 7);
INSERT INTO Uczniowie VALUES (101, 'Wojciech', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (102, 'Bartosz', 'Gowicki', 7);
INSERT INTO Uczniowie VALUES (103, 'Jakub', 'Ruwecki', 7);
INSERT INTO Uczniowie VALUES (104, 'Jakub', 'Biwacki', 7);
INSERT INTO Uczniowie VALUES (105, 'Hubert', 'Drzewacki', 7);
INSERT INTO Uczniowie VALUES (106, 'Wojciech', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (107, 'Bartosz', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (108, 'Jakub', 'Ruwecki', 8);
INSERT INTO Uczniowie VALUES (109, 'Jakub', 'Biwacki', 8);
INSERT INTO Uczniowie VALUES (110, 'Hubert', 'Drzewacki', 8);
INSERT INTO Uczniowie VALUES (111, 'Wojciech', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (112, 'Bartosz', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (113, 'Jakub', 'Ruwecki', 8);
INSERT INTO Uczniowie VALUES (114, 'Jakub', 'Biwacki', 8);
INSERT INTO Uczniowie VALUES (115, 'Hubert', 'Drzewacki', 8);
INSERT INTO Uczniowie VALUES (116, 'Wojciech', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (117, 'Bartosz', 'Gowicki', 8);
INSERT INTO Uczniowie VALUES (118, 'Jakub', 'Ruwecki', 8);
INSERT INTO Uczniowie VALUES (119, 'Jakub', 'Biwacki', 8);
INSERT INTO Uczniowie VALUES (120, 'Hubert', 'Drzewacki', 8);
INSERT INTO Uczniowie VALUES (121, 'Wojciech', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (122, 'Bartosz', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (123, 'Jakub', 'Ruwecki', 9);
INSERT INTO Uczniowie VALUES (124, 'Jakub', 'Biwacki', 9);
INSERT INTO Uczniowie VALUES (125, 'Hubert', 'Drzewacki', 9);
INSERT INTO Uczniowie VALUES (126, 'Wojciech', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (127, 'Bartosz', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (128, 'Jakub', 'Ruwecki', 9);
INSERT INTO Uczniowie VALUES (129, 'Jakub', 'Biwacki', 9);
INSERT INTO Uczniowie VALUES (130, 'Hubert', 'Drzewacki', 9);
INSERT INTO Uczniowie VALUES (131, 'Wojciech', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (132, 'Bartosz', 'Gowicki', 9);
INSERT INTO Uczniowie VALUES (133, 'Jakub', 'Ruwecki', 9);
INSERT INTO Uczniowie VALUES (134, 'Jakub', 'Biwacki', 9);
INSERT INTO Uczniowie VALUES (135, 'Hubert', 'Drzewacki', 9);
INSERT INTO Uczniowie VALUES (136, 'Wojciech', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (137, 'Bartosz', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (138, 'Jakub', 'Ruwecki', 10);
INSERT INTO Uczniowie VALUES (139, 'Jakub', 'Biwacki', 10);
INSERT INTO Uczniowie VALUES (140, 'Hubert', 'Drzewacki', 10);
INSERT INTO Uczniowie VALUES (141, 'Wojciech', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (142, 'Bartosz', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (143, 'Jakub', 'Ruwecki', 10);
INSERT INTO Uczniowie VALUES (144, 'Jakub', 'Biwacki', 10);
INSERT INTO Uczniowie VALUES (145, 'Hubert', 'Drzewacki', 10);
INSERT INTO Uczniowie VALUES (146, 'Wojciech', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (147, 'Bartosz', 'Gowicki', 10);
INSERT INTO Uczniowie VALUES (148, 'Jakub', 'Ruwecki', 10);
INSERT INTO Uczniowie VALUES (149, 'Jakub', 'Biwacki', 10);
INSERT INTO Uczniowie VALUES (150, 'Hubert', 'Drzewacki', 10);
INSERT INTO Uczniowie VALUES (151, 'Wojciech', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (152, 'Bartosz', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (153, 'Jakub', 'Ruwecki', 11);
INSERT INTO Uczniowie VALUES (154, 'Jakub', 'Biwacki', 11);
INSERT INTO Uczniowie VALUES (155, 'Hubert', 'Drzewacki', 11);
INSERT INTO Uczniowie VALUES (156, 'Wojciech', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (157, 'Bartosz', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (158, 'Jakub', 'Ruwecki', 11);
INSERT INTO Uczniowie VALUES (159, 'Jakub', 'Biwacki', 11);
INSERT INTO Uczniowie VALUES (160, 'Hubert', 'Drzewacki', 11);
INSERT INTO Uczniowie VALUES (161, 'Wojciech', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (162, 'Bartosz', 'Gowicki', 11);
INSERT INTO Uczniowie VALUES (163, 'Jakub', 'Ruwecki', 11);
INSERT INTO Uczniowie VALUES (164, 'Jakub', 'Biwacki', 11);
INSERT INTO Uczniowie VALUES (165, 'Hubert', 'Drzewacki', 11);
INSERT INTO Uczniowie VALUES (166, 'Wojciech', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (167, 'Bartosz', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (168, 'Jakub', 'Ruwecki', 12);
INSERT INTO Uczniowie VALUES (169, 'Jakub', 'Biwacki', 12);
INSERT INTO Uczniowie VALUES (170, 'Hubert', 'Drzewacki', 12);
INSERT INTO Uczniowie VALUES (171, 'Wojciech', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (172, 'Bartosz', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (173, 'Jakub', 'Ruwecki', 12);
INSERT INTO Uczniowie VALUES (174, 'Jakub', 'Biwacki', 12);
INSERT INTO Uczniowie VALUES (175, 'Hubert', 'Drzewacki', 12);
INSERT INTO Uczniowie VALUES (176, 'Wojciech', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (177, 'Bartosz', 'Gowicki', 12);
INSERT INTO Uczniowie VALUES (178, 'Jakub', 'Ruwecki', 12);
INSERT INTO Uczniowie VALUES (179, 'Jakub', 'Biwacki', 12);
INSERT INTO Uczniowie VALUES (180, 'Hubert', 'Drzewacki', 12);
-----------
INSERT INTO Konkretne_przedmioty VALUES (1, 1, 1, 1);
INSERT INTO Konkretne_przedmioty VALUES (2, 1, 2, 1);
INSERT INTO Konkretne_przedmioty VALUES (3, 1, 3, 1);
INSERT INTO Konkretne_przedmioty VALUES (4, 1, 4, 2);
INSERT INTO Konkretne_przedmioty VALUES (5, 1, 5, 2);
INSERT INTO Konkretne_przedmioty VALUES (6, 1, 6, 2);
INSERT INTO Konkretne_przedmioty VALUES (7, 1, 7, 3);
INSERT INTO Konkretne_przedmioty VALUES (8, 1, 8, 3);
INSERT INTO Konkretne_przedmioty VALUES (9, 1, 9, 3);
INSERT INTO Konkretne_przedmioty VALUES (10, 1, 10, 4);
INSERT INTO Konkretne_przedmioty VALUES (11, 1, 11, 4);
INSERT INTO Konkretne_przedmioty VALUES (12, 1, 12, 4);
INSERT INTO Konkretne_przedmioty VALUES (13, 2, 1, 5);
INSERT INTO Konkretne_przedmioty VALUES (14, 2, 2, 5);
INSERT INTO Konkretne_przedmioty VALUES (15, 2, 3, 5);
INSERT INTO Konkretne_przedmioty VALUES (16, 2, 4, 6);
INSERT INTO Konkretne_przedmioty VALUES (17, 2, 5, 6);
INSERT INTO Konkretne_przedmioty VALUES (18, 2, 6, 6);
INSERT INTO Konkretne_przedmioty VALUES (19, 2, 7, 7);
INSERT INTO Konkretne_przedmioty VALUES (20, 2, 8, 7);
INSERT INTO Konkretne_przedmioty VALUES (21, 2, 9, 7);
INSERT INTO Konkretne_przedmioty VALUES (22, 2, 10, 8);
INSERT INTO Konkretne_przedmioty VALUES (23, 2, 11, 8);
INSERT INTO Konkretne_przedmioty VALUES (24, 2, 12, 8);
INSERT INTO Konkretne_przedmioty VALUES (25, 3, 1, 9);
INSERT INTO Konkretne_przedmioty VALUES (26, 3, 2, 9);
INSERT INTO Konkretne_przedmioty VALUES (27, 3, 3, 9);
INSERT INTO Konkretne_przedmioty VALUES (28, 3, 4, 10);
INSERT INTO Konkretne_przedmioty VALUES (29, 3, 5, 10);
INSERT INTO Konkretne_przedmioty VALUES (30, 3, 6, 10);
INSERT INTO Konkretne_przedmioty VALUES (31, 3, 7, 11);
INSERT INTO Konkretne_przedmioty VALUES (32, 3, 8, 11);
INSERT INTO Konkretne_przedmioty VALUES (33, 3, 9, 11);
INSERT INTO Konkretne_przedmioty VALUES (34, 3, 10, 12);
INSERT INTO Konkretne_przedmioty VALUES (35, 3, 11, 12);
INSERT INTO Konkretne_przedmioty VALUES (36, 3, 12, 12);
INSERT INTO Konkretne_przedmioty VALUES (37, 4, 1, 13);
INSERT INTO Konkretne_przedmioty VALUES (38, 4, 2, 13);
INSERT INTO Konkretne_przedmioty VALUES (39, 4, 3, 13);
INSERT INTO Konkretne_przedmioty VALUES (40, 4, 4, 14);
INSERT INTO Konkretne_przedmioty VALUES (41, 4, 5, 14);
INSERT INTO Konkretne_przedmioty VALUES (42, 4, 6, 14);
INSERT INTO Konkretne_przedmioty VALUES (43, 4, 7, 15);
INSERT INTO Konkretne_przedmioty VALUES (44, 4, 8, 15);
INSERT INTO Konkretne_przedmioty VALUES (45, 4, 9, 15);
INSERT INTO Konkretne_przedmioty VALUES (46, 4, 10, 16);
INSERT INTO Konkretne_przedmioty VALUES (47, 4, 11, 16);
INSERT INTO Konkretne_przedmioty VALUES (48, 4, 12, 16);
INSERT INTO Konkretne_przedmioty VALUES (49, 5, 1, 17);
INSERT INTO Konkretne_przedmioty VALUES (50, 5, 2, 17);
INSERT INTO Konkretne_przedmioty VALUES (51, 5, 3, 17);
INSERT INTO Konkretne_przedmioty VALUES (52, 5, 4, 18);
INSERT INTO Konkretne_przedmioty VALUES (53, 5, 5, 18);
INSERT INTO Konkretne_przedmioty VALUES (54, 5, 6, 18);
INSERT INTO Konkretne_przedmioty VALUES (55, 5, 7, 19);
INSERT INTO Konkretne_przedmioty VALUES (56, 5, 8, 19);
INSERT INTO Konkretne_przedmioty VALUES (57, 5, 9, 19);
INSERT INTO Konkretne_przedmioty VALUES (58, 5, 10, 20);
INSERT INTO Konkretne_przedmioty VALUES (59, 5, 11, 20);
INSERT INTO Konkretne_przedmioty VALUES (60, 5, 12, 20);
INSERT INTO Konkretne_przedmioty VALUES (61, 6, 1, 21);
INSERT INTO Konkretne_przedmioty VALUES (62, 6, 2, 21);
INSERT INTO Konkretne_przedmioty VALUES (63, 6, 3, 21);
INSERT INTO Konkretne_przedmioty VALUES (64, 6, 4, 22);
INSERT INTO Konkretne_przedmioty VALUES (65, 6, 5, 22);
INSERT INTO Konkretne_przedmioty VALUES (66, 6, 6, 22);
INSERT INTO Konkretne_przedmioty VALUES (67, 6, 7, 23);
INSERT INTO Konkretne_przedmioty VALUES (68, 6, 8, 23);
INSERT INTO Konkretne_przedmioty VALUES (69, 6, 9, 23);
INSERT INTO Konkretne_przedmioty VALUES (70, 6, 10, 24);
INSERT INTO Konkretne_przedmioty VALUES (71, 6, 11, 24);
INSERT INTO Konkretne_przedmioty VALUES (72, 6, 12, 24);
-----------
INSERT INTO Oceny_uczniow VALUES (1, 1, 7, '14/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (2, 1, 13, '21/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (3, 1, 13, '16/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (4, 2, 14, '18/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (5, 2, 14, '11/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (6, 2, 1, '23/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (7, 3, 2, '13/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (8, 3, 11, '18/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (9, 3, 14, '29/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (10, 4, 14, '25/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (11, 4, 4, '14/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (12, 4, 4, '20/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (13, 5, 1, '24/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (14, 5, 13, '22/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (15, 5, 14, '22/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (16, 6, 7, '14/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (17, 6, 1, '20/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (18, 6, 10, '19/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (19, 7, 1, '20/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (20, 7, 1, '28/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (21, 7, 12, '19/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (22, 8, 4, '23/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (23, 8, 9, '26/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (24, 8, 11, '20/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (25, 9, 14, '22/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (26, 9, 14, '22/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (27, 9, 8, '15/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (28, 10, 8, '20/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (29, 10, 6, '15/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (30, 10, 12, '28/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (31, 11, 10, '14/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (32, 11, 9, '29/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (33, 11, 2, '11/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (34, 12, 4, '24/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (35, 12, 1, '13/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (36, 12, 3, '11/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (37, 13, 3, '28/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (38, 13, 13, '16/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (39, 13, 3, '11/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (40, 14, 6, '29/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (41, 14, 9, '25/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (42, 14, 7, '28/11/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (43, 15, 14, '13/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (44, 15, 2, '11/10/2022', 1, null);
INSERT INTO Oceny_uczniow VALUES (45, 15, 8, '15/10/2022', 1, null);
-----------
